
name: Deploy via FTP

on:
  push:
    branches:
      - main  # MantÃ©m o deploy automÃ¡tico ao fazer push
  workflow_dispatch: # Adiciona o gatilho manual via interface

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Pegando o cÃ³digo mais recente
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: ðŸ“‚ Enviando para o servidor via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./public_html/  # Caminho da pasta dentro do seu servidor
